const ingredients = [{ name: "mango", unit: "grams", quantity: 150 }, { name: "toasted cashews", unit: "cup", quantity: 0.75 }, { name: "balsamic vinegar", unit: "tablespoon", quantity: 1 }, { name: "ground cinnamon", unit: "teaspoon", quantity: 0.5 }, { name: "ground ginger", unit: "teaspoon", quantity: 0.25 }, { name: "salt", unit: "teaspoon", quantity: 0.125 }] 

 const response = [
    {
        "sugar_g": 4.3,
        "fiber_g": 9.2,
        "serving_size_g": 100,
        "sodium_mg": 495,
        "name": "cereal",
        "potassium_mg": 489,
        "fat_saturated_g": 1.5,
        "fat_total_g": 6.8,
        "calories": 386,
        "cholesterol_mg": 0,
        "protein_g": 12.2,
        "carbohydrates_total_g": 71.9
    },
    {
        "sugar_g": 2.2,
        "fiber_g": 3.4,
        "serving_size_g": 100,
        "sodium_mg": 1216,
        "name": "pretzels",
        "potassium_mg": 127,
        "fat_saturated_g": 0.4,
        "fat_total_g": 2.9,
        "calories": 389.1,
        "cholesterol_mg": 0,
        "protein_g": 10.1,
        "carbohydrates_total_g": 81.2
    },
    {
        "sugar_g": 5.9,
        "fiber_g": 5.6,
        "serving_size_g": 100,
        "sodium_mg": 3,
        "name": "green peas",
        "potassium_mg": 115,
        "fat_saturated_g": 0,
        "fat_total_g": 0.2,
        "calories": 82.6,
        "cholesterol_mg": 0,
        "protein_g": 5.4,
        "carbohydrates_total_g": 15.9
    },
    {
        "sugar_g": 9.8,
        "fiber_g": 11.3,
        "serving_size_g": 100,
        "sodium_mg": 22,
        "name": "roasted chickpeas",
        "potassium_mg": 233,
        "fat_saturated_g": 1.7,
        "fat_total_g": 13.6,
        "calories": 412.7,
        "cholesterol_mg": 0,
        "protein_g": 18.9,
        "carbohydrates_total_g": 57.7
    },
    {
        "sugar_g": 2.2,
        "fiber_g": 5.3,
        "serving_size_g": 100,
        "sodium_mg": 6,
        "name": "edamames",
        "potassium_mg": 169,
        "fat_saturated_g": 0.6,
        "fat_total_g": 5.2,
        "calories": 124.2,
        "cholesterol_mg": 0,
        "protein_g": 11.9,
        "carbohydrates_total_g": 9.1
    },
    {
        "sugar_g": 4.6,
        "fiber_g": 10.7,
        "serving_size_g": 100,
        "sodium_mg": 498,
        "name": "roasted almonds",
        "potassium_mg": 470,
        "fat_saturated_g": 3.9,
        "fat_total_g": 51.9,
        "calories": 588.2,
        "cholesterol_mg": 0,
        "protein_g": 21,
        "carbohydrates_total_g": 21
    },
    {
        "sugar_g": 0.3,
        "fiber_g": 9.8,
        "serving_size_g": 100,
        "sodium_mg": 768,
        "name": "popcorn",
        "potassium_mg": 272,
        "fat_saturated_g": 14.5,
        "fat_total_g": 30.7,
        "calories": 549.3,
        "cholesterol_mg": 0,
        "protein_g": 8.5,
        "carbohydrates_total_g": 57
    },
    {
        "sugar_g": 10.4,
        "fiber_g": 35.1,
        "serving_size_g": 100,
        "sodium_mg": 67,
        "name": "smoked paprika",
        "potassium_mg": 312,
        "fat_saturated_g": 2.2,
        "fat_total_g": 13,
        "calories": 289.2,
        "cholesterol_mg": 0,
        "protein_g": 14.2,
        "carbohydrates_total_g": 52.9
    },
    {
        "sugar_g": 0,
        "fiber_g": 0,
        "serving_size_g": 100,
        "sodium_mg": 38395,
        "name": "salt",
        "potassium_mg": 0,
        "fat_saturated_g": 0,
        "fat_total_g": 0,
        "calories": 0,
        "cholesterol_mg": 0,
        "protein_g": 0,
        "carbohydrates_total_g": 0
    },
    {
        "sugar_g": 0,
        "fiber_g": 0,
        "serving_size_g": 100,
        "sodium_mg": 1,
        "name": "olive oil",
        "potassium_mg": 0,
        "fat_saturated_g": 13.9,
        "fat_total_g": 101.2,
        "calories": 869.2,
        "cholesterol_mg": 0,
        "protein_g": 0,
        "carbohydrates_total_g": 0
    },
    {
        "sugar_g": 59.9,
        "fiber_g": 0,
        "serving_size_g": 100,
        "sodium_mg": 11,
        "name": "maple syrup",
        "potassium_mg": 1,
        "fat_saturated_g": 0,
        "fat_total_g": 0,
        "calories": 267.5,
        "cholesterol_mg": 0,
        "protein_g": 0.1,
        "carbohydrates_total_g": 67.8
    }
]